### ISSUE TITLE
Move as much code as possible to Pipeline and Liblouis 

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-celia#48]
### Hyphenation

- [ ] Hyphenation tables could be moved to dedicated project and published on Maven central. Pipeline could then use these tables as the default for Finnish.

   A [new project](https://github.com/celiafi/celia-hyphenation-tables) has been created and [a package has been deployed to Github](https://github.com/celiafi/celia-hyphenation-tables/packages/1312116) but it's currently a snapshot (1.5.1-SNAPSHOT). I need a release (1.0.0) that I can include in Pipeline.

### Braille translation

- [x] This project contains two Celia specific Liblouis tables.
  - additional-symbols.utb: these three symbols have already been moved upstream in 2016 (https://github.com/liblouis/liblouis/pull/165)
  - undefined.utb: the new `(dots-for-undefined-char:...)` feature can be used instead
- [ ] `block-translate.xsl` does not seem to contain anything Celia specific so can be eliminated
- [ ] `CeliaTranslator` can be eliminated too.

### Braille output format

- [x] The PEF processing that happens in post-processing.xpl should be part of the Pipeline's capability to configure the output braille file format (the "output-file-format" option). The following features should be ported:
  - [x] option to make sure that the back of the last sheet is not printed (see insert-empty-pages.xsl): this can be done with `(blank-last-page)`
  - [x] option to insert pages to make the volumes divisible by 4 (when printed in magazine layout) (see pad-sections.xsl and postprocess-volumes.xsl): this can be done with `(sheets-multiple-of-two)`

### Style sheets and custom script options that map to Sass variables

Everything below is about porting CSS code, which is not required to be able to make use of the generic Pipeline because CSS can be supplied as input to a conversion and therefore does not need to be included in pipeline-mod-celia. Custom options that are solely used to set Sass variables can now be handled with the "Style sheet parameters" option. In other words consider these points optimizations rather than required steps.

- [ ] Table of contents: see [SBS](https://github.com/sbsdev/pipeline-mod-sbs/issues/75)
- [ ] Print page break indication: see [NLB](https://github.com/nlbdev/pipeline/issues/225)
- [ ] Production notes: see [SBS](https://github.com/sbsdev/pipeline-mod-sbs/issues/75)
- [ ] Images: see [NLB](https://github.com/nlbdev/pipeline/issues/225)
- [ ] Captions: see [NLB](https://github.com/nlbdev/pipeline/issues/225)
- [x] Notes: done: see the "Notes placement" option (http://daisy.github.io/pipeline/Get-Help/User-Guide/Scripts/html-to-pef/)

**Comment by bertfrees** [comment]
I consider my contribution to solving this issue more or less done now. I'm only waiting for a release of [celia-hyphenation-tables](https://github.com/celiafi/celia-hyphenation-tables), so that I can include it in Pipeline. I might port some more CSS code in the future but that has lower priority.
